api:
  type: completion
  streaming: true
  headers:
    x-slo-ttft-ms: '600'
    x-slo-tpot-ms: '50'
  slo_unit: ms
data:
  type: synthetic
  input_distribution:
    # To ensure consistent load for accurate performance comparison:
    # - 'min' and 'max' are set to the same value as 'mean'.
    # - 'std_dev' is set to 0 to eliminate variance in token length.
    min: 4096
    max: 4096
    mean: 4096
    std_dev: 0
  output_distribution:
    min: 512
    max: 512
    mean: 512
    std_dev: 0
load:
  type: constant
  interval: 1.0
  stages:
    # low -> high -> low -> high -> low
    - rate: 4.0
      duration: 150
    - rate: 32.0
      duration: 30
    - rate: 4.0
      duration: 150
    - rate: 32.0
      duration: 30
    - rate: 4.0
      duration: 150
  worker_max_concurrency: 8
server:
  type: vllm
  model_name: meta-llama/Llama-3.1-8B-Instruct
  base_url: <LLM API URL>
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
metrics:
  type: prometheus
  prometheus:
    url: <PROMETHEUS_URL>
    scrape_interval: 15
report:
  prometheus:
    summary: true
    per_stage: false
  session_lifecycle:
    summary: true
    per_stage: true
    per_session: false
