apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: {{ include "poolName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "llm-d-inference-scheduler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "poolName" . }}
  endpointPickerRef:
    name: {{ include "modelName" . }}-endpoint-picker
    kind: Service
    port:
      number: 9002
  targetPorts:
  - number: 8000
