{{- if or (eq .Values.preset "default") (eq .Values.preset "poc") }}
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu
  namespace: {{ .Values.namespace }}
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.nvidia.com
{{- end }}
