---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poolName" . }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ include "poolName" . }}
  sessionAffinity: None
  type: ClusterIP
